name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for reporting a bug!

        Please fill out this form to help us understand and fix the issue.

        💡 **Tip**: Tag @claude in a comment after creating this issue to get AI-powered analysis and suggestions!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Messages / Stack Trace
      description: Include any error messages or stack traces
      placeholder: Paste error messages here
      render: shell

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application is affected?
      options:
        - API / FastAPI
        - Database / SQLAlchemy
        - Deck Analyzer
        - CSV Parser
        - Embeddings
        - SmartInference (OpenAI)
        - SmartMemory
        - SmartSQL
        - MCP Server
        - Tests
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of arena-improver are you using?
      placeholder: "e.g., 0.1.0, main branch, commit SHA"

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Information about your environment
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, macOS 14, Windows 11]
        - Python version: [e.g., 3.11.5]
        - Installation method: [e.g., pip, Docker, source]
      value: |
        - OS:
        - Python version:
        - Installation method:

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem
      placeholder: Screenshots, logs, related issues, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this hasn't been reported
          required: true
        - label: I have included all relevant error messages and stack traces
          required: false
        - label: I can reproduce this issue consistently
          required: false
        - label: I have checked the documentation
          required: false

  - type: markdown
    attributes:
      value: |
        ---

        ## 🤖 Want AI assistance?

        After creating this issue, you can tag **@claude** in a comment to get:
        - Automated root cause analysis
        - Suggested fixes with code examples
        - Related issues and solutions
        - Testing strategies

        Example: `@claude can you help analyze this bug?`
